# Generated by Django 3.0.8 on 2020-07-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=100, verbose_name='Estado')),
                ('latitude', models.PositiveIntegerField(verbose_name='Latitude')),
                ('longitude', models.PositiveIntegerField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro')], verbose_name='Sexo')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('tipo', models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
